rel_path: "/xdysite"
title: xdy小站
description: welcome
author: xdyydx
email: jhr32272@outlook.com
github: https://github.com/xdyydx
headimgall: False
headercolor: #de7112
navcolor: #3e7112
bgcolor: #1b9114
footercolor: #fff614
