rel_path: "/xdysite"
title: xdy小站
description: welcome
author: xdyydx
email: jhr32272@outlook.com
github: https://github.com/xdyydx
headimgall: False
headercolor: #de7112
navcolor: #4e7112
bgcolor: 
footercolor: 
